# Generated by Django 5.0.6 on 2024-05-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appetizers',
            name='img',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='breads_rotis',
            name='img',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deserts',
            name='img',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='img',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rice_items',
            name='img',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='side_dishes',
            name='img',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='soups_salads',
            name='img',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='special_curries',
            name='img',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
