# Generated by Django 5.0.6 on 2024-06-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_appetizers_img_alter_breads_rotis_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_placed',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
