# Generated by Django 5.0.6 on 2024-06-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_orders_placed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_placed',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
