# Generated by Django 5.0.6 on 2024-07-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_customer_address_customer_phoneno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_placed',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
