# Generated by Django 5.0.6 on 2024-07-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_orders_placed_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='appetizers',
            name='availability',
            field=models.CharField(default='Available', max_length=20),
        ),
        migrations.AddField(
            model_name='breads_rotis',
            name='availability',
            field=models.CharField(default='Available', max_length=20),
        ),
        migrations.AddField(
            model_name='deserts',
            name='availability',
            field=models.CharField(default='Available', max_length=20),
        ),
        migrations.AddField(
            model_name='drinks',
            name='availability',
            field=models.CharField(default='Available', max_length=20),
        ),
        migrations.AddField(
            model_name='rice_items',
            name='availability',
            field=models.CharField(default='Available', max_length=20),
        ),
        migrations.AddField(
            model_name='side_dishes',
            name='availability',
            field=models.CharField(default='Available', max_length=20),
        ),
        migrations.AddField(
            model_name='soups_salads',
            name='availability',
            field=models.CharField(default='Available', max_length=20),
        ),
        migrations.AddField(
            model_name='special_curries',
            name='availability',
            field=models.CharField(default='Available', max_length=20),
        ),
    ]
